=== DarthSC18/Web-Des-/timetable.dtd
<!ELEMENT timetable (day, class+)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT class (subject, startTime, endTime, teacher, room)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT endTime (#PCDATA)>
<!ELEMENT teacher (#PCDATA)>
<!ELEMENT room (#PCDATA)>

=== DarthSC18/Web-Des-/monday_timetable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "timetable.dtd">
<timetable>
  <day>Monday</day>

  <class>
    <subject>DBMS Practicals (Batch - 1)</subject>
    <startTime>08:00</startTime>
    <endTime>10:00</endTime>
    <teacher>Roy Sir</teacher>
    <room>XKC</room>
  </class>

  <class>
    <subject>Web Dev</subject>
    <startTime>11:00</startTime>
    <endTime>12:00</endTime>
    <teacher>Bertilda Ma'am</teacher>
    <room>LR20B</room>
  </class>

  <class>
    <subject>DBMS</subject>
    <startTime>12:00</startTime>
    <endTime>13:00</endTime>
    <teacher>Roy Sir</teacher>
    <room>LR20B</room>
  </class>

  <class>
    <subject>OOPS</subject>
    <startTime>14:00</startTime>
    <endTime>15:00</endTime>
    <teacher>Subash Sir</teacher>
    <room>LR33</room>
  </class>

</timetable>
